//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoundIt_final2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoundList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoundList()
        {
            this.Histories = new HashSet<History>();
        }
    
        public string foundID { get; set; }
        public string itemID { get; set; }
        public string userID { get; set; }
        public string foundLocation { get; set; }
        public string officeLocation { get; set; }
        public string foundStatus { get; set; }
    
        public virtual LostList LostList { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
    }
}
