//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoundIt_final2
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public string historyID { get; set; }
        public string itemID { get; set; }
        public string ownerID { get; set; }
        public string foundID { get; set; }
        public string userFoundID { get; set; }
        public string itemDescription { get; set; }
        public string foundLocation { get; set; }
    
        public virtual FoundList FoundList { get; set; }
        public virtual LostList LostList { get; set; }
    }
}
