//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoundIt_final2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LostList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LostList()
        {
            this.FoundLists = new HashSet<FoundList>();
            this.Histories = new HashSet<History>();
        }
    
        public string itemID { get; set; }
        public string itemName { get; set; }
        public string itemType { get; set; }
        public string itemDescription { get; set; }
        public string LastLocation { get; set; }
        public string ownerID { get; set; }
        public string itemStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoundList> FoundLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
        public virtual User User { get; set; }
    }
}
